services:
  db:
    image: postgres
    container_name: autosalone-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

# database per i test
  db-test:
    image: postgres
    container_name: autosalone-test-db
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-test:/var/lib/postgresql

volumes:
  pgdata:
  pgdata-test: